In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
%pip install matplotlib pandas seaborn numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\dell\appdata\roaming\python\python313\site-packages (3.10.9)
Requirement already satisfied: pandas in c:\users\dell\appdata\roaming\python\python313\site-packages (3.0.1)
Requirement already satisfied: seaborn in c:\users\dell\appdata\roaming\python\python313\site-packages (0.13.2)
Requirement already satisfied: numpy in c:\users\dell\appdata\roaming\python\python313\site-packages (2.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\roaming\python\python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\DDO-Semiconductor-main\DDO-Semiconductor-main\data\ChipPerformance.csv")
df

,Unnamed: 0,Product,Type,Release Date,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),Foundry,Vendor,FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
0,0,AMD Athlon 64 3500+,CPU,2007-02-20,65.0,45.0,77.0,122.0,2200.0,Unknown,AMD,NaN,NaN,NaN
1,1,AMD Athlon 200GE,CPU,2018-09-06,14.0,35.0,192.0,4800.0,3200.0,Unknown,AMD,NaN,NaN,NaN
2,2,Intel Core i5-1145G7,CPU,2020-09-02,10.0,28.0,NaN,NaN,2600.0,Intel,Intel,NaN,NaN,NaN
3,3,Intel Xeon E5-2603 v2,CPU,2013-09-01,22.0,80.0,160.0,1400.0,1800.0,Intel,Intel,NaN,NaN,NaN
4,4,AMD Phenom II X4 980 BE,CPU,2011-05-03,45.0,125.0,258.0,758.0,3700.0,Unknown,AMD,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4849,4849,NVIDIA Quadro 3000M,GPU,2011-02-22,40.0,75.0,332.0,1950.0,450.0,TSMC,NVIDIA,NaN,432.0,36.0
4850,4850,Intel GMA 950,GPU,2005-06-01,90.0,7.0,NaN,NaN,250.0,Intel,Intel,NaN,NaN,NaN
4851,4851,NVIDIA GeForce GT 320M,GPU,2010-03-03,40.0,23.0,100.0,486.0,500.0,TSMC,NVIDIA,NaN,52.8,NaN
4852,4852,NVIDIA GeForce FX 5200,GPU,2003-03-06,150.0,NaN,65.0,29.0,250.0,TSMC,NVIDIA,NaN,NaN,NaN
4853,4853,NVIDIA GeForce 9300 SE,GPU,2008-06-01,65.0,NaN,86.0,210.0,540.0,TSMC,NVIDIA,NaN,20.8,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4854 entries, 0 to 4853
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             4854 non-null   int64
 1   Product                4854 non-null   str
 2   Type                   4854 non-null   str
 3   Release Date           4854 non-null   str
 4   Process Size (nm)      4845 non-null   float64
 5   TDP (W)                4228 non-null   float64
 6   Die Size (mm^2)        4139 non-null   float64
 7   Transistors (million)  4143 non-null   float64
 8   Freq (MHz)             4854 non-null   float64
 9   Foundry                4854 non-null   str
 10  Vendor                 4854 non-null   str
 11  FP16 GFLOPS            536 non-null    float64
 12  FP32 GFLOPS            1948 non-null   float64
 13  FP64 GFLOPS            1306 non-null   float64
dtypes: float64(8), int64(1), str(5)
memory usage: 531.0 KB

In [7]:
df.describe()

,Unnamed: 0,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
count,4854.000000,4845.000000,4228.000000,4139.000000,4143.000000,4854.000000,536.000000,1948.000000,1306.000000
mean,2426.500000,55.109598,81.359981,188.440445,1929.922279,1484.406057,8397.459851,2134.756653,363.670511
std,1401.373433,44.998676,76.807808,126.189383,4044.891098,1066.701523,13799.551131,3898.431487,1145.931856
min,0.000000,0.000000,1.000000,1.000000,8.000000,100.000000,10.020000,12.800000,3.600000
25%,1213.250000,22.000000,33.000000,104.000000,154.000000,590.000000,768.800000,257.300000,38.295000
50%,2426.500000,40.000000,65.000000,148.000000,624.000000,1073.500000,2965.500000,696.000000,89.280000
75%,3639.750000,90.000000,100.000000,239.000000,1550.000000,2400.000000,10600.000000,2116.750000,220.000000
max,4853.000000,250.000000,900.000000,826.000000,54200.000000,4700.000000,184600.000000,40000.000000,11540.000000

In [16]:
df.isnull().sum()/len(df)*100

Unnamed: 0                0.000000
Product                   0.000000
Type                      0.000000
Release Date              0.000000
Process Size (nm)         0.185414
TDP (W)                  12.896580
Die Size (mm^2)          14.730119
Transistors (million)    14.647713
Freq (MHz)                0.000000
Foundry                   0.000000
Vendor                    0.000000
FP16 GFLOPS              88.957561
FP32 GFLOPS              59.868150
FP64 GFLOPS              73.094355
dtype: float64

In [15]:
(df==0).sum()

Unnamed: 0               1
Product                  0
Type                     0
Release Date             0
Process Size (nm)        4
TDP (W)                  0
Die Size (mm^2)          0
Transistors (million)    0
Freq (MHz)               0
Foundry                  0
Vendor                   0
FP16 GFLOPS              0
FP32 GFLOPS              0
FP64 GFLOPS              0
dtype: int64

In [25]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Product, Type, Release Date, Process Size (nm), TDP (W), Die Size (mm^2), Transistors (million), Freq (MHz), Foundry, Vendor, FP16 GFLOPS, FP32 GFLOPS, FP64 GFLOPS]
Index: []

In [31]:
df["Product"].value_counts().head(10)

Product
AMD Athlon 64 3200+    12
AMD Athlon 64 3000+    10
AMD Sempron 3000+      10
Intel HD Graphics      10
AMD Athlon 64 3500+     9
AMD Sempron 2800+       9
AMD Sempron 3100+       7
AMD Athlon 64 3400+     7
AMD Sempron 2600+       6
AMD Athlon 64 3800+     6
Name: count, dtype: int64

In [32]:
df[df["Product"]== "Intel HD Graphics" ]

,Unnamed: 0,Product,Type,Release Date,Process Size (nm),TDP (W),Die Size (mm^2),Transistors (million),Freq (MHz),Foundry,Vendor,FP16 GFLOPS,FP32 GFLOPS,FP64 GFLOPS
2205,2205,Intel HD Graphics,GPU,2013-04-29,22.0,45.0,NaN,NaN,200.0,Intel,Intel,NaN,136.00,34.00
2465,2465,Intel HD Graphics,GPU,2010-01-10,45.0,35.0,114.0,177.0,533.0,Intel,Intel,NaN,102.30,NaN
2613,2613,Intel HD Graphics,GPU,2013-04-29,22.0,45.0,NaN,NaN,200.0,Intel,Intel,NaN,160.00,40.00
3020,3020,Intel HD Graphics,GPU,2012-04-01,22.0,NaN,94.0,392.0,650.0,Intel,Intel,NaN,100.80,25.20
3184,3184,Intel HD Graphics,GPU,2013-09-02,22.0,4.0,NaN,NaN,311.0,Intel,Intel,NaN,41.34,10.34
3568,3568,Intel HD Graphics,GPU,2010-01-10,45.0,35.0,114.0,177.0,133.0,Intel,Intel,NaN,96.00,NaN
3847,3847,Intel HD Graphics,GPU,2012-10-01,22.0,45.0,94.0,392.0,350.0,Intel,Intel,NaN,96.00,24.00
4360,4360,Intel HD Graphics,GPU,2015-01-05,14.0,6.0,82.0,NaN,100.0,Intel,Intel,NaN,153.60,38.40
4753,4753,Intel HD Graphics,GPU,2011-05-01,32.0,NaN,131.0,504.0,350.0,Intel,Intel,NaN,76.80,NaN
4757,4757,Intel HD Graphics,GPU,2015-04-01,14.0,6.0,NaN,NaN,500.0,Intel,Intel,NaN,96.00,24.00